import 'dart:io';

void main() async {
  final file = File('lib/data/vocabulary_data.dart');
  var content = await file.readAsString();

  // Turkish character replacements
  final replacements = <String, String>{
    // Category titles
    'Kisisel Koruyucu Ekipman': 'Kişisel Koruyucu Ekipman',
    'Emniyet Isaretleri': 'Emniyet İşaretleri',
    'Isyeri Tehlikeleri': 'İşyeri Tehlikeleri',
    'Temel Atolye Aletleri': 'Temel Atölye Aletleri',
    'Guvenlik Dokumantasyonu': 'Güvenlik Dokümantasyonu',
    'Atolye Uygulamalari': 'Atölye Uygulamaları',
    'Malzeme Tasima': 'Malzeme Taşıma',
    'Atolye Ekipmanlari': 'Atölye Ekipmanları',
    'Aviyonik Test Ekipmanlari': 'Aviyonik Test Ekipmanları',
    'Muhendislik Cizimleri': 'Mühendislik Çizimleri',
    'Percinleme': 'Perçinleme',
    'Sokme ve Onarim': 'Sökme ve Onarım',
    'Ucak Yapilari': 'Uçak Yapıları',
    'Pnomatik Sistemler': 'Pnömatik Sistemler',
    'Ucus Kontrol Sistemleri': 'Uçuş Kontrol Sistemleri',
    'Kapali Alan Girisi': 'Kapalı Alan Girişi',
    'Dusme Korumasi': 'Düşme Koruması',
    'Sicak Calisma Guvenligi': 'Sıcak Çalışma Güvenliği',
    'Kimyasal Guvenlik': 'Kimyasal Güvenlik',
    'Elektrik Guvenligi': 'Elektrik Güvenliği',
    'Yangin Acil Durumu': 'Yangın Acil Durumu',
    'Tibbi Acil Durum': 'Tıbbi Acil Durum',
    'Tehlikeli Madde Mudahalesi': 'Tehlikeli Madde Müdahalesi',
    'Ucak Acil Durumu': 'Uçak Acil Durumu',
    'Acil Durumlarda Iletisim': 'Acil Durumlarda İletişim',
    'Ilk Yardim ve CPR': 'İlk Yardım ve CPR',
    'Havacilik Yakitlari': 'Havacılık Yakıtları',
    'Yangin Sondurme Ekipmanlari': 'Yangın Söndürme Ekipmanları',
    'Ucak Hareketi': 'Uçak Hareketi',
    'Kokpit Islemleri': 'Kokpit İşlemleri',
    'Yakit Sistemleri': 'Yakıt Sistemleri',

    // Common Turkish word fixes - most specific first
    'emniyet kaski': 'emniyet kaskı',
    'koruyucu gozluk': 'koruyucu gözlük',
    'emniyet botlari': 'emniyet botları',
    'gorunurluk yelegi': 'görünürlük yeleği',
    'isitme korumasi': 'işitme koruması',
    'yuz siperi': 'yüz siperi',
    'dusme koruma kemeri': 'düşme koruma kemeri',
    'celik burun': 'çelik burun',
    'kulak tikaci': 'kulak tıkacı',
    'kulaklik': 'kulaklık',
    'kimyasal dayanikli eldiven': 'kimyasal dayanıklı eldiven',
    'guvenlik halati': 'güvenlik halatı',
    'guvenlik kemeri tutturma noktasi': 'güvenlik kemeri tutturma noktası',

    'uyari isareti': 'uyarı işareti',
    'dikkat isareti': 'dikkat işareti',
    'tehlike isareti': 'tehlike işareti',
    'acil cikis': 'acil çıkış',
    'yangin sondurucu': 'yangın söndürücü',
    'sigara icilmez': 'sigara içilmez',
    'yanici madde': 'yanıcı madde',
    'yuksek gerilim': 'yüksek gerilim',
    'koruyucu gozluk zorunlu': 'koruyucu gözlük zorunlu',
    'baret zorunlu bolge': 'baret zorunlu bölge',
    'ilk yardim istasyonu': 'ilk yardım istasyonu',
    'toplanma noktasi': 'toplanma noktası',
    'tehlikeli atik': 'tehlikeli atık',
    'asindirici madde': 'aşındırıcı madde',

    'yangin tehlikesi': 'yangın tehlikesi',
    'kimyasal dokulme': 'kimyasal dökülme',
    'takilma tehlikesi': 'takılma tehlikesi',
    'dusen nesneler': 'düşen nesneler',
    'hareketli makina': 'hareketli makine',
    'kapali alan': 'kapalı alan',
    'oksijen eksikligi': 'oksijen eksikliği',
    'patlayici atmosfer': 'patlayıcı atmosfer',
    'sicak yuzey': 'sıcak yüzey',
    'gurultu maruziyeti': 'gürültü maruziyeti',
    'titresim tehlikesi': 'titreşim tehlikesi',

    'cekic': 'çekiç',
    'allen anahtari': 'allen anahtarı',
    'duz tornavida': 'düz tornavida',
    'yildiz tornavida': 'yıldız tornavida',
    'maket bicagi': 'maket bıçağı',
    'serit metre': 'şerit metre',
    'ege': 'eğe',

    'gunluk kayit defteri': 'günlük kayıt defteri',
    'is emri': 'iş emri',
    'bakim el kitabi': 'bakım el kitabı',
    'guvenlik bilgi formu': 'güvenlik bilgi formu',
    'calisma izni': 'çalışma izni',
    'risk degerlendirmesi': 'risk değerlendirmesi',
    'kalibrasyon sertifikasi': 'kalibrasyon sertifikası',
    'egitim kaydi': 'eğitim kaydı',
    'ucusa elverislilik direktifi': 'uçuşa elverişlilik direktifi',
    'duzeltici faaliyet': 'düzeltici faaliyet',

    'isyeri guvenligi': 'işyeri güvenliği',
    'yangin onlemleri': 'yangın önlemleri',
    'acil durum irtibatlari': 'acil durum irtibatları',
    'yangin alarmlari': 'yangın alarmları',
    'tahliye yollari': 'tahliye yolları',
    'risk degerlendirmeleri': 'risk değerlendirmeleri',
    'elektrik guvenligi': 'elektrik güvenliği',
    'is sagligi ve guvenligi mevzuati': 'iş sağlığı ve güvenliği mevzuatı',
    'isyeri temizligi': 'işyeri temizliği',
    'yangin guvenligi': 'yangın güvenliği',
    'elle tasima': 'elle taşıma',
    'gaz tupleri': 'gaz tüpleri',
    'yangin yonetmelikleri': 'yangın yönetmelikleri',

    'alet bakimi': 'alet bakımı',
    'alet kontrolu': 'alet kontrolü',
    'alet kullanimi': 'alet kullanımı',
    'atolye malzemeleri': 'atölye malzemeleri',
    'atik bertarafi': 'atık bertarafı',
    'atolye duzeni': 'atölye düzeni',
    'guvenlik prosedurleri': 'güvenlik prosedürleri',
    'temizlik ve yaglama': 'temizlik ve yağlama',
    'alet takimlari': 'alet takımları',
    'ekipman kullanimi': 'ekipman kullanımı',
    'tezgah bakimi': 'tezgah bakımı',
    'elektrikli alet guvenligi': 'elektrikli alet güvenliği',

    'malzeme tasima': 'malzeme taşıma',
    'malzeme guvenligi': 'malzeme güvenliği',
    'atolye deposu': 'atölye deposu',
    'malzeme yonetimi': 'malzeme yönetimi',
    'malzeme kontrolu': 'malzeme kontrolü',
    'sivi yonetimi': 'sıvı yönetimi',
    'asindirici tasima': 'aşındırıcı taşıma',
    'malzeme guvenlik bilgi formlari': 'malzeme güvenlik bilgi formları',
    'sivi depolama': 'sıvı depolama',
    'yangin guvenlik malzemeleri': 'yangın güvenlik malzemeleri',
    'malzeme tasima prosedurleri': 'malzeme taşıma prosedürleri',
    'yanici malzemeler': 'yanıcı malzemeler',
    'malzeme envanter yonetimi': 'malzeme envanter yönetimi',
    'malzeme tasima guvenligi': 'malzeme taşıma güvenliği',

    'kelepce': 'kelepçe',
    'taslama tezgahi': 'taşlama tezgahı',
    'taslama diski': 'taşlama diski',
    'el torpusu': 'el törpüsü',
    'kesme sivisi': 'kesme sıvısı',
    'yaglayici': 'yağlayıcı',
    'ayakli matkap': 'ayaklı matkap',
    'sutunlu matkap': 'sütunlu matkap',
    'tel firca diski': 'tel fırça diski',
    'capak alma aleti': 'çapak alma aleti',
    'duz torpu': 'düz törpü',
    'yuvarlak torpu': 'yuvarlak törpü',
    'sogutucu': 'soğutucu',

    'akim olcumu': 'akım ölçümü',
    'gerilim olcumu': 'gerilim ölçümü',
    'transformator metreleri': 'transformatör metreleri',
    'baglanti test cihazlari': 'bağlantı test cihazları',
    'metre dogrulugu': 'metre doğruluğu',
    'test ekipmani kalibrasyonu': 'test ekipmanı kalibrasyonu',
    'test prosedurleri': 'test prosedürleri',
    'cift bobinli metreler': 'çift bobinli metreler',
    'aku testi': 'akü testi',
    'baglanti ve topraklama testleri': 'bağlantı ve topraklama testleri',

    'teknik cizimler': 'teknik çizimler',
    'muhendislik standartlari': 'mühendislik standartları',
    'kesit gorunumleri': 'kesit görünümleri',
    'malzeme ozellikleri': 'malzeme özellikleri',
    'cizim tanimlamasi': 'çizim tanımlaması',
    'geometrik boyutlandirma ve tolerans':
        'geometrik boyutlandırma ve tolerans',
    'eskiz cizimi': 'eskiz çizimi',
    'sematikler': 'şematikler',
    'montaj diyagramlari': 'montaj diyagramları',
    'uretim standartlari': 'üretim standartları',
    'CAD cizimleri': 'CAD çizimleri',
    'imalat cizimleri': 'imalat çizimleri',
    'uluslararasi standartlar': 'uluslararası standartlar',
    'mekanik cizimler': 'mekanik çizimler',
    'tasarim cizimleri': 'tasarım çizimleri',

    'percinleme teknikleri': 'perçinleme teknikleri',
    'dolu percinler': 'dolu perçinler',
    'percin turleri': 'perçin türleri',
    'percin tanimlamasi': 'perçin tanımlaması',
    'percin boyutlandirma': 'perçin boyutlandırma',
    'percin yerlesimi': 'perçin yerleşimi',
    'percin montaji': 'perçin montajı',
    'percin boslugu': 'perçin boşluğu',
    'percin kavrama uzunlugu': 'perçin kavrama uzunluğu',
    'percin paylari': 'perçin payları',
    'baglanti elemanlari': 'bağlantı elemanları',
    'percinleme aletleri': 'perçinleme aletleri',
    'pnomatik percinleyiciler': 'pnömatik perçinleyiciler',
    'elle percinleme': 'elle perçinleme',
    'percin muayenesi': 'perçin muayenesi',
    'percin sokumu': 'perçin sökümü',
    'percin kusurlari': 'perçin kusurları',
    'gomme percinleme': 'gömme perçinleme',
    'havsa basli percinler': 'havşa başlı perçinler',
    'percin basi turleri': 'perçin başı türleri',
    'percinleme prosedurleri': 'perçinleme prosedürleri',

    'bilyali yataklar': 'bilyalı yataklar',
    'makarali yataklar': 'makaralı yataklar',
    'yatak turleri': 'yatak türleri',
    'yatak yaglamasi': 'yatak yağlaması',
    'yatak temizligi': 'yatak temizliği',
    'yatak sokumu': 'yatak sökümü',
    'yatak arizasi': 'yatak arızası',
    'acisal temasli yataklar': 'açısal temaslı yataklar',
    'silindirik makarali yataklar': 'silindirik makaralı yataklar',
    'kuresel makarali yataklar': 'küresel makaralı yataklar',
    'yatak kusurlari': 'yatak kusurları',
    'yatak contalari': 'yatak contaları',
    'yatak boslugu': 'yatak boşluğu',
    'yatak asinmasi': 'yatak aşınması',
    'yatak bakimi': 'yatak bakımı',
    'yatak degisimi': 'yatak değişimi',
    'yatak toleranslari': 'yatak toleransları',

    'sert lehim yontemleri': 'sert lehim yöntemleri',
    'yumusak lehimleme': 'yumuşak lehimleme',
    'gumus lehimleme': 'gümüş lehimleme',
    'TIG kaynagi': 'TIG kaynağı',
    'MIG kaynagi': 'MIG kaynağı',
    'elle metal ark kaynagi': 'elle metal ark kaynağı',
    'kaynak kusurlari': 'kaynak kusurları',
    'kaynak guvenligi': 'kaynak güvenliği',
    'dolgu cubuklari': 'dolgu çubukları',
    'yapistirici ajanlar': 'yapıştırıcı ajanlar',
    'yapistirici ile birlestirme': 'yapıştırıcı ile birleştirme',
    'kaynak guvenlik ekipmani': 'kaynak güvenlik ekipmanı',
    'yangin riskleri': 'yangın riskleri',

    'sokme teknikleri': 'sökme teknikleri',
    'muayene yontemleri': 'muayene yöntemleri',
    'onarim prosedurleri': 'onarım prosedürleri',
    'bilesen sokumu': 'bileşen sökümü',
    'yapisal onarimlar': 'yapısal onarımlar',
    'percin onarimlari': 'perçin onarımları',
    'bilesen muayenesi': 'bileşen muayenesi',
    'parca degisimi': 'parça değişimi',
    'hasar degerlendirmesi': 'hasar değerlendirmesi',
    'parca tanimlamasi': 'parça tanımlaması',
    'onarim kitleri': 'onarım kitleri',
    'onarim aletleri': 'onarım aletleri',
    'hasar siniflandirmasi': 'hasar sınıflandırması',
    'onarim dokumantasyonu': 'onarım dokümantasyonu',
    'montaj standartlari': 'montaj standartları',
    'muayene standartlari': 'muayene standartları',
    'baglanti elemani montaji': 'bağlantı elemanı montajı',

    'govde': 'gövde',
    'kuyruk takimi': 'kuyruk takımı',
    'stabilizor': 'stabilizör',
    'dumen': 'dümen',
    'irtifa dumeni': 'irtifa dümeni',
    'kanatcik': 'kanatçık',
    'fren kanadi': 'fren kanadı',
    'inis takimi': 'iniş takımı',
    'burun takimi': 'burun takımı',
    'ana takimi': 'ana takımı',
    'motor yuvasi': 'motor yuvası',

    'hidrolik sivi': 'hidrolik sıvı',
    'hidrolik aktuator': 'hidrolik aktüatör',
    'basinc gostergesi': 'basınç göstergesi',
    'akumulator': 'akümülatör',
    'guc paketi': 'güç paketi',
    'basinc tahliye valfi': 'basınç tahliye valfi',
    'cek valf': 'çek valf',

    'jenerator': 'jeneratör',
    'transformator': 'transformatör',
    'invertor': 'invertör',
    'redresor': 'redresör',
    'role': 'röle',
    'gerilim regulatoru': 'gerilim regülatörü',
    'akim sinirlandirici': 'akım sınırlandırıcı',
    'toprak hatasi': 'toprak hatası',
    'yuk atma': 'yük atma',
    'harici guc': 'harici güç',
    'APU jeneratori': 'APU jeneratörü',

    'yakit tanki': 'yakıt tankı',
    'yakit pompasi': 'yakıt pompası',
    'yakit filtresi': 'yakıt filtresi',
    'yakit hatti': 'yakıt hattı',
    'yakit valfi': 'yakıt valfi',
    'yakit selektoru': 'yakıt selektörü',
    'yakit gostergesi': 'yakıt göstergesi',
    'yakit kapagi': 'yakıt kapağı',
    'yakit havalandirma': 'yakıt havalandırma',
    'yakit suzgeci': 'yakıt süzgeci',
    'capraz besleme valfi': 'çapraz besleme valfi',
    'yakit miktar gostergesi': 'yakıt miktar göstergesi',
    'yakit isitici': 'yakıt ısıtıcı',
    'su ayirici': 'su ayırıcı',
    'yakit bosaltma': 'yakıt boşaltma',

    'kanama havasi': 'kanama havası',
    'pnomatik valf': 'pnömatik valf',
    'basinlandirma': 'basınlandırma',
    'cikis valfi': 'çıkış valfi',
    'kabin irtifasi': 'kabin irtifası',
    'diferansiyel basinc': 'diferansiyel basınç',
    'hava dongu makinesi': 'hava döngü makinesi',
    'isi degistirici': 'ısı değiştirici',
    'karisim valfi': 'karışım valfi',
    'resirkulasyon fani': 'resirkülasyon fanı',
    'motor kanamasi': 'motor kanaması',
    'APU kanamasi': 'APU kanaması',
    'kanat buz onleme': 'kanat buz önleme',
    'yagmur itici': 'yağmur itici',

    'trim kanati': 'trim kanadı',
    'ucus bilgisayari': 'uçuş bilgisayarı',
    'it-cek cubugu': 'it-çek çubuğu',
    'kol mekanizmasi': 'kol mekanizması',
    'tork tubu': 'tork tübü',
    'his unitesi': 'his ünitesi',
    'kumanda sarsici': 'kumanda sarsıcı',
    'sapma sondurucusu': 'sapma söndürücüsü',
    'stol korumasi': 'stol koruması',

    'hizmet disi etiketi': 'hizmet dışı etiketi',
    'kilit baglamasi': 'kilit bağlaması',
    'sifir enerji durumu': 'sıfır enerji durumu',
    'dogrulama': 'doğrulama',
    'vardiya degisimi': 'vardiya değişimi',
    'kaldir proseduru': 'kaldır prosedürü',
    'enerji kaynagi': 'enerji kaynağı',

    'giris izni': 'giriş izni',
    'havalandirma': 'havalandırma',
    'yanici gaz': 'yanıcı gaz',
    'giris supervisoru': 'giriş süpervizörü',
    'refakatci': 'refakatçi',
    'giren kisi': 'giren kişi',
    'iletisim sistemi': 'iletişim sistemi',
    'acil cikarma': 'acil çıkarma',
    'geri cekim sistemi': 'geri çekim sistemi',
    'hava monitoru': 'hava monitörü',

    'dusme tutucu': 'düşme tutucu',
    'guvenlik kemeri': 'güvenlik kemeri',
    'baglanti noktasi': 'bağlantı noktası',
    'bag ipi': 'bağ ipi',
    'kendi cekilen halat': 'kendi çekilen halat',
    'sok emici': 'şok emici',
    'on kenar': 'ön kenar',
    'dusme mesafesi': 'düşme mesafesi',
    'guvenlik agi': 'güvenlik ağı',
    'kisisel dusme sinirlandirici': 'kişisel düşme sınırlandırıcı',
    'tam vucut kemeri': 'tam vücut kemeri',
    'sirt halkasi': 'sırt halkası',
    'kurtarma plani': 'kurtarma planı',
    'yetkili kisi': 'yetkili kişi',

    'sicak calisma izni': 'sıcak çalışma izni',
    'yangin nobeti': 'yangın nöbeti',
    'kivilcim kontrolu': 'kıvılcım kontrolü',
    'yangin battaniyesi': 'yangın battaniyesi',
    'yanici malzeme': 'yanıcı malzeme',
    'geri tepme tutucu': 'geri tepme tutucu',
    'arindirma': 'arındırma',
    'gaz tupu depolama': 'gaz tüpü depolama',
    'tup ayirma': 'tüp ayırma',
    'is sonrasi muayene': 'iş sonrası muayene',
    'yangin nobeti suresi': 'yangın nöbeti süresi',

    'malzeme guvenlik formu': 'malzeme güvenlik formu',
    'tehlike sembolu': 'tehlike sembolü',
    'havalandirma gereksinimi': 'havalandırma gereksinimi',
    'dokuntu kiti': 'döküntü kiti',
    'goz yikama istasyonu': 'göz yıkama istasyonu',
    'ikincil cevirme': 'ikincil çevirme',
    'kimyasal atik': 'kimyasal atık',
    'ilk yardim onlemleri': 'ilk yardım önlemleri',
    'acil dus': 'acil duş',

    'elektrik carpmasi': 'elektrik çarpması',
    'canli kablo': 'canlı kablo',
    'devre test cihazi': 'devre test cihazı',
    'ark parlamasi': 'ark parlaması',
    'ark patlamasi': 'ark patlaması',
    'elektrik yaniklari': 'elektrik yanıkları',
    'toprak hatasi devre kesici': 'toprak hatası devre kesici',
    'elektrik panosu guvenligi': 'elektrik panosu güvenliği',
    'dogrulama cihazi': 'doğrulama cihazı',
    'sinirlar': 'sınırlar',

    'tahliye plani': 'tahliye planı',
    'kisi sayimi': 'kişi sayımı',
    'tahliye tatbikati': 'tahliye tatbikatı',
    'kat gorevlisi': 'kat görevlisi',
    'siginak alani': 'sığınak alanı',
    'merdiven boslugu': 'merdiven boşluğu',
    'yeniden giris proseduru': 'yeniden giriş prosedürü',
    'ozel ihtiyac tahliyesi': 'özel ihtiyaç tahliyesi',

    'PASS teknigi': 'PASS tekniği',
    'pimi cek': 'pimi çek',
    'kolu sik': 'kolu sık',
    'saga sola surukle': 'sağa sola sürükle',
    'yangin ucgeni': 'yangın üçgeni',
    'sinif A yangin': 'sınıf A yangın',
    'sinif B yangin': 'sınıf B yangın',
    'sinif C yangin': 'sınıf C yangın',
    'sinif D yangin': 'sınıf D yangın',
    'yangin bastirma sistemi': 'yangın bastırma sistemi',
    'yangin sorusturmasi': 'yangın soruşturması',
    'yangin hasar degerlendirmesi': 'yangın hasar değerlendirmesi',

    'tibbi acil durum': 'tıbbi acil durum',
    'ilk mudahaleci': 'ilk müdahaleci',
    'yasam belirtileri': 'yaşam belirtileri',
    'bilincli': 'bilinçli',
    'bilincsiz': 'bilinçsiz',
    'nabiz': 'nabız',
    'otomatik defibrilator': 'otomatik defibrilatör',
    'omurga yaralanmasi': 'omurga yaralanması',
    'hareketsizlestirme': 'hareketsizleştirme',
    'tibbi transport': 'tıbbi transport',
    'triaj': 'triyaj',

    'dokuntu mudahalesi': 'döküntü müdahalesi',
    'cevirme': 'çevirme',
    'notralize': 'nötralize',
    'dekontaminasyon bolgesi': 'dekontaminasyon bölgesi',
    'yasak bolge': 'yasak bölge',
    'sicak bolge': 'sıcak bölge',
    'ilik bolge': 'ılık bölge',
    'soguk bolge': 'soğuk bölge',
    'bagimsiz solunum cihazi': 'bağımsız solunum cihazı',
    'kimyasala direncli': 'kimyasala dirençli',
    'acil mudahale kilavuzu': 'acil müdahale kılavuzu',

    'acil inis': 'acil iniş',
    'cakisma kurtarma': 'çakışma kurtarma',
    'itfaiye araci': 'itfaiye aracı',
    'kopuk uygulama': 'köpük uygulama',
    'acil kaydiran': 'acil kaydıran',
    'kanat ustu cikis': 'kanat üstü çıkış',
    'carpisma pozisyonu': 'çarpışma pozisyonu',
    'kurtulan cikarma': 'kurtulan çıkarma',
    'triaj alani': 'triyaj alanı',
    'yarali toplama': 'yaralı toplama',
    'birlesik komuta': 'birleşik komuta',
    'olay komutani': 'olay komutanı',
    'karsilikli yardim': 'karşılıklı yardım',
    'havaalani acil plan': 'havaalanı acil plan',

    'mayday cagrisi': 'mayday çağrısı',
    'pan-pan cagrisi': 'pan-pan çağrısı',
    'telsiz iletisimi': 'telsiz iletişimi',
    'acil isareti': 'acil işareti',
    'cakisma pozisyon gostergesi': 'çakışma pozisyon göstergesi',
    'el isareti': 'el işareti',
    'acil kod sozcukleri': 'acil kod sözcükleri',
    'yedek iletisim': 'yedek iletişim',

    'ilk yardim': 'ilk yardım',
    'yanik': 'yanık',
    'bilincsizlik': 'bilinçsizlik',
    'kalp akciger canlandirma': 'kalp akciğer canlandırma',
    'dolasim': 'dolaşım',
    'gogus kompresyonlari': 'göğüs kompresyonları',
    'kirik': 'kırık',
    'sok': 'şok',
    'kalp durmasi': 'kalp durması',
    'yari yuzukoyun pozisyon': 'yarı yüzükoyun pozisyon',
    'tehlike-yanit-yardim-hava yolu-nefes-dolasim':
        'tehlike-yanıt-yardım-hava yolu-nefes-dolaşım',
    'canlandirma': 'canlandırma',

    'havacilik yakiti': 'havacılık yakıtı',
    'gazyagi': 'gazyağı',
    'yakit ikmali': 'yakıt ikmali',
    'yakit buhari': 'yakıt buharı',
    'baglama kablosu': 'bağlama kablosu',
    'yakit dokulmesi': 'yakıt dökülmesi',
    'buhar basinci': 'buhar basıncı',
    'parlama noktasi': 'parlama noktası',
    'yakit kirliligi': 'yakıt kirliliği',
    'topraklama kayisi': 'topraklama kayışı',
    'anti-statik katki': 'anti-statik katkı',

    'kopuklu sondurucu': 'köpüklü söndürücü',
    'CO2 sondurucu': 'CO2 söndürücü',
    'kuru tozlu sondurucu': 'kuru tozlu söndürücü',
    'yangin hortumu': 'yangın hortumu',
    'yangin muslugu': 'yangın musluğu',
    'yagmurlama sistemi': 'yağmurlama sistemi',
    'duman dedektoru': 'duman dedektörü',
    'yangin alarm paneli': 'yangın alarm paneli',
    'acil durum aydinlatmasi': 'acil durum aydınlatması',
    'yangin kapisi': 'yangın kapısı',
    'sondurucu muayenesi': 'söndürücü muayenesi',
    'yangin tatbikati': 'yangın tatbikatı',
    'yangin ekibi': 'yangın ekibi',

    'cekilme': 'çekilme',
    'park yonlendirme': 'park yönlendirme',
    'cekme cubugu': 'çekme çubuğu',
    'yer guc unitesi': 'yer güç ünitesi',
    'hava baslangic unitesi': 'hava başlangıç ünitesi',
    'bagaj yukleyici': 'bagaj yükleyici',
    'ikram araci': 'ikram aracı',
    'buz cozme araci': 'buz çözme aracı',
    'yakit kamyonu': 'yakıt kamyonu',
    'koprulu binis': 'köprülü biniş',

    'bekleme noktasi': 'bekleme noktası',
    'yer kontrolu': 'yer kontrolü',
    'kanat gozcusu': 'kanat gözcüsü',
    'takip araci': 'takip aracı',
    'fren birakma': 'fren bırakma',
    'motor calistirma izni': 'motor çalıştırma izni',
    'taksi talimatlari': 'taksi talimatları',

    'ucus guverte': 'uçuş güverte',
    'gosterge paneli': 'gösterge paneli',
    'dumen pedallari': 'dümen pedalları',
    'ucus yonetim sistemi': 'uçuş yönetim sistemi',
    'birincil ucus ekrani': 'birincil uçuş ekranı',
    'navigasyon ekrani': 'navigasyon ekranı',
    'motor gostergeleri': 'motor göstergeleri',
    'ucus kontrol unitesi': 'uçuş kontrol ünitesi',
    'yedek gostergeler': 'yedek göstergeler',

    // UNITE fixes
    'UNITE': 'ÜNİTE',
  };

  // Apply all replacements
  replacements.forEach((old, newVal) {
    content = content.replaceAll(old, newVal);
  });

  await file.writeAsString(content);
  // Türkçe karakter düzeltmeleri tamamlandı!
}
