# -*- coding: utf-8 -*-
import re

# Read the file
with open('lib/data/vocabulary_data.dart', 'r', encoding='utf-8') as f:
    content = f.read()

# Turkish character replacements - order matters!
replacements = [
    # Specific words first (longer matches)
    ('Kisisel Koruyucu Ekipman', 'Kişisel Koruyucu Ekipman'),
    ('Emniyet Isaretleri', 'Emniyet İşaretleri'),
    ('Isyeri Tehlikeleri', 'İşyeri Tehlikeleri'),
    ('Temel Atolye Aletleri', 'Temel Atölye Aletleri'),
    ('Guvenlik Dokumantasyonu', 'Güvenlik Dokümantasyonu'),
    ('Emniyet Tedbirleri', 'Emniyet Tedbirleri'),
    ('Atolye Uygulamalari', 'Atölye Uygulamaları'),
    ('Malzeme Tasima', 'Malzeme Taşıma'),
    ('Atolye Ekipmanlari', 'Atölye Ekipmanları'),
    ('Aviyonik Test Ekipmanlari', 'Aviyonik Test Ekipmanları'),
    ('Muhendislik Cizimleri', 'Mühendislik Çizimleri'),
    ('Percinleme', 'Perçinleme'),
    ('Kaynak ve Lehimleme', 'Kaynak ve Lehimleme'),
    ('Sokme ve Onarim', 'Sökme ve Onarım'),
    ('Ucak Yapilari', 'Uçak Yapıları'),
    ('Hidrolik Sistemler', 'Hidrolik Sistemler'),
    ('Elektrik Sistemleri', 'Elektrik Sistemleri'),
    ('Yakit Sistemleri', 'Yakıt Sistemleri'),
    ('Pnomatik Sistemler', 'Pnömatik Sistemler'),
    ('Ucus Kontrol Sistemleri', 'Uçuş Kontrol Sistemleri'),
    ('Kilitleme Etiketleme', 'Kilitleme Etiketleme'),
    ('Kapali Alan Girisi', 'Kapalı Alan Girişi'),
    ('Dusme Korumasi', 'Düşme Koruması'),
    ('Sicak Calisma Guvenligi', 'Sıcak Çalışma Güvenliği'),
    ('Kimyasal Guvenlik', 'Kimyasal Güvenlik'),
    ('Elektrik Guvenligi', 'Elektrik Güvenliği'),
    ('Acil Tahliye', 'Acil Tahliye'),
    ('Yangin Acil Durumu', 'Yangın Acil Durumu'),
    ('Tibbi Acil Durum', 'Tıbbi Acil Durum'),
    ('Tehlikeli Madde Mudahalesi', 'Tehlikeli Madde Müdahalesi'),
    ('Ucak Acil Durumu', 'Uçak Acil Durumu'),
    ('Acil Durumlarda Iletisim', 'Acil Durumlarda İletişim'),
    ('Ilk Yardim ve CPR', 'İlk Yardım ve CPR'),
    ('Havacilik Yakitlari', 'Havacılık Yakıtları'),
    ('Yangin Sondurme Ekipmanlari', 'Yangın Söndürme Ekipmanları'),
    ('Yer Hizmetleri', 'Yer Hizmetleri'),
    ('Ucak Hareketi', 'Uçak Hareketi'),
    ('Kokpit Islemleri', 'Kokpit İşlemleri'),
    
    # Common Turkish word fixes
    ('emniyet kaski', 'emniyet kaskı'),
    ('koruyucu gozluk', 'koruyucu gözlük'),
    ('emniyet botlari', 'emniyet botları'),
    ('gorunurluk yelegi', 'görünürlük yeleği'),
    ('isitme korumasi', 'işitme koruması'),
    ('emniyet eldivenleri', 'emniyet eldivenleri'),
    ('yuz siperi', 'yüz siperi'),
    ('solunum maskesi', 'solunum maskesi'),
    ('dusme koruma kemeri', 'düşme koruma kemeri'),
    ('celik burun', 'çelik burun'),
    ('kulak tikaci', 'kulak tıkacı'),
    ('kulaklik', 'kulaklık'),
    ('koruyucu tulum', 'koruyucu tulum'),
    ('dizlik', 'dizlik'),
    ('anti-statik giysi', 'anti-statik giysi'),
    ('kimyasal dayanikli eldiven', 'kimyasal dayanıklı eldiven'),
    ('guvenlik halati', 'güvenlik halatı'),
    ('guvenlik kemeri tutturma noktasi', 'güvenlik kemeri tutturma noktası'),
    
    # Safety signs
    ('uyari isareti', 'uyarı işareti'),
    ('dikkat isareti', 'dikkat işareti'),
    ('tehlike isareti', 'tehlike işareti'),
    ('acil cikis', 'acil çıkış'),
    ('yangin sondurucu', 'yangın söndürücü'),
    ('sigara icilmez', 'sigara içilmez'),
    ('yanici madde', 'yanıcı madde'),
    ('yuksek gerilim', 'yüksek gerilim'),
    ('koruyucu gozluk zorunlu', 'koruyucu gözlük zorunlu'),
    ('baret zorunlu bolge', 'baret zorunlu bölge'),
    ('ilk yardim istasyonu', 'ilk yardım istasyonu'),
    ('toplanma noktasi', 'toplanma noktası'),
    ('sadece yetkili personel', 'sadece yetkili personel'),
    ('tehlikeli atik', 'tehlikeli atık'),
    ('asindirici madde', 'aşındırıcı madde'),
    ('radyasyon tehlikesi', 'radyasyon tehlikesi'),
    ('kaygan zemin', 'kaygan zemin'),
    
    # Workplace hazards
    ('yangin tehlikesi', 'yangın tehlikesi'),
    ('elektrik tehlikesi', 'elektrik tehlikesi'),
    ('kimyasal dokulme', 'kimyasal dökülme'),
    ('zehirli dumanlar', 'zehirli dumanlar'),
    ('kayma tehlikesi', 'kayma tehlikesi'),
    ('takilma tehlikesi', 'takılma tehlikesi'),
    ('dusen nesneler', 'düşen nesneler'),
    ('hareketli makina', 'hareketli makine'),
    ('kapali alan', 'kapalı alan'),
    ('oksijen eksikligi', 'oksijen eksikliği'),
    ('patlayici atmosfer', 'patlayıcı atmosfer'),
    ('sicak yuzey', 'sıcak yüzey'),
    ('gurultu maruziyeti', 'gürültü maruziyeti'),
    ('titresim tehlikesi', 'titreşim tehlikesi'),
    ('ergonomik risk', 'ergonomik risk'),
    ('tehlikeli madde', 'tehlikeli madde'),
    ('kilitleme etiketleme', 'kilitleme etiketleme'),
    
    # Basic tools
    ('anahtar', 'anahtar'),
    ('tornavida', 'tornavida'),
    ('cekic', 'çekiç'),
    ('pense', 'pense'),
    ('ayarlanabilir anahtar', 'ayarlanabilir anahtar'),
    ('lokma anahtar', 'lokma anahtar'),
    ('allen anahtari', 'allen anahtarı'),
    ('duz tornavida', 'düz tornavida'),
    ('yildiz tornavida', 'yıldız tornavida'),
    ('kargaburun pense', 'kargaburun pense'),
    ('tel kesici', 'tel kesici'),
    ('maket bicagi', 'maket bıçağı'),
    ('serit metre', 'şerit metre'),
    ('terazi', 'terazi'),
    ('keski', 'keski'),
    ('ege', 'eğe'),
    ('testere', 'testere'),
    
    # Safety documentation
    ('gunluk kayit defteri', 'günlük kayıt defteri'),
    ('is emri', 'iş emri'),
    ('muayene raporu', 'muayene raporu'),
    ('bakim el kitabi', 'bakım el kitabı'),
    ('guvenlik bilgi formu', 'güvenlik bilgi formu'),
    ('calisma izni', 'çalışma izni'),
    ('risk degerlendirmesi', 'risk değerlendirmesi'),
    ('olay raporu', 'olay raporu'),
    ('kalibrasyon sertifikasi', 'kalibrasyon sertifikası'),
    ('egitim kaydi', 'eğitim kaydı'),
    ('uygunluk kontrol listesi', 'uygunluk kontrol listesi'),
    ('ucusa elverislilik direktifi', 'uçuşa elverişlilik direktifi'),
    ('kalite kontrol formu', 'kalite kontrol formu'),
    ('uygunsuzluk raporu', 'uygunsuzluk raporu'),
    ('duzeltici faaliyet', 'düzeltici faaliyet'),
    ('yetkili imza', 'yetkili imza'),
    ('mevzuata uygunluk', 'mevzuata uygunluk'),
    
    # Safety precautions  
    ('isyeri guvenligi', 'işyeri güvenliği'),
    ('yangin onlemleri', 'yangın önlemleri'),
    ('acil durum irtibatlari', 'acil durum irtibatları'),
    ('yangin alarmlari', 'yangın alarmları'),
    ('tahliye yollari', 'tahliye yolları'),
    ('kaza raporlama', 'kaza raporlama'),
    ('risk degerlendirmeleri', 'risk değerlendirmeleri'),
    ('tehlikeli maddeler', 'tehlikeli maddeler'),
    ('elektrik guvenligi', 'elektrik güvenliği'),
    ('kimyasal tehlikeler', 'kimyasal tehlikeler'),
    ('is sagligi ve guvenligi mevzuati', 'iş sağlığı ve güvenliği mevzuatı'),
    ('isyeri temizligi', 'işyeri temizliği'),
    ('yangin guvenligi', 'yangın güvenliği'),
    ('elle tasima', 'elle taşıma'),
    ('gaz tupleri', 'gaz tüpleri'),
    ('oksijen sistemleri', 'oksijen sistemleri'),
    ('yangin yonetmelikleri', 'yangın yönetmelikleri'),
    
    # Workshop practices
    ('alet bakimi', 'alet bakımı'),
    ('alet kontrolu', 'alet kontrolü'),
    ('el aletleri', 'el aletleri'),
    ('elektrikli aletler', 'elektrikli aletler'),
    ('kalibrasyon', 'kalibrasyon'),
    ('alet deposu', 'alet deposu'),
    ('alet kullanimi', 'alet kullanımı'),
    ('hassas aletler', 'hassas aletler'),
    ('atolye malzemeleri', 'atölye malzemeleri'),
    ('tehlikeli malzemeler', 'tehlikeli malzemeler'),
    ('atik bertarafi', 'atık bertarafı'),
    ('atolye duzeni', 'atölye düzeni'),
    ('guvenlik prosedurleri', 'güvenlik prosedürleri'),
    ('makine aletleri', 'makine aletleri'),
    ('temizlik ve yaglama', 'temizlik ve yağlama'),
    ('alet muayenesi', 'alet muayenesi'),
    ('alet takimlari', 'alet takımları'),
    ('ekipman kullanimi', 'ekipman kullanımı'),
    ('tezgah bakimi', 'tezgah bakımı'),
    ('elektrikli alet guvenligi', 'elektrikli alet güvenliği'),
    
    # Material handling
    ('malzeme tasima', 'malzeme taşıma'),
    ('malzeme guvenligi', 'malzeme güvenliği'),
    ('atolye deposu', 'atölye deposu'),
    ('malzeme yonetimi', 'malzeme yönetimi'),
    ('malzeme kontrolu', 'malzeme kontrolü'),
    ('sivi yonetimi', 'sıvı yönetimi'),
    ('asindirici tasima', 'aşındırıcı taşıma'),
    ('malzeme guvenlik bilgi formlari', 'malzeme güvenlik bilgi formları'),
    ('sivi depolama', 'sıvı depolama'),
    ('yangin guvenlik malzemeleri', 'yangın güvenlik malzemeleri'),
    ('malzeme tasima prosedurleri', 'malzeme taşıma prosedürleri'),
    ('yanici malzemeler', 'yanıcı malzemeler'),
    ('malzeme envanter yonetimi', 'malzeme envanter yönetimi'),
    ('malzeme tasima guvenligi', 'malzeme taşıma güvenliği'),
    
    # Workshop equipment
    ('mengene', 'mengene'),
    ('kelepce', 'kelepçe'),
    ('matkap presi', 'matkap presi'),
    ('demir testeresi', 'demir testeresi'),
    ('taslama tezgahi', 'taşlama tezgahı'),
    ('taslama diski', 'taşlama diski'),
    ('el torpusu', 'el törpüsü'),
    ('kesme sivisi', 'kesme sıvısı'),
    ('yaglayici', 'yağlayıcı'),
    ('ayakli matkap', 'ayaklı matkap'),
    ('sutunlu matkap', 'sütunlu matkap'),
    ('tel firca diski', 'tel fırça diski'),
    ('capak alma aleti', 'çapak alma aleti'),
    ('duz torpu', 'düz törpü'),
    ('yuvarlak torpu', 'yuvarlak törpü'),
    ('testere gerilimi', 'testere gerilimi'),
    ('sogutucu', 'soğutucu'),
    
    # Avionic test
    ('aviyonik testi', 'aviyonik testi'),
    ('pitot-statik testi', 'pitot-statik testi'),
    ('analog metreler', 'analog metreler'),
    ('izolasyon testi', 'izolasyon testi'),
    ('akim olcumu', 'akım ölçümü'),
    ('gerilim olcumu', 'gerilim ölçümü'),
    ('transformator metreleri', 'transformatör metreleri'),
    ('rasyo metreleri', 'rasyo metreleri'),
    ('baglanti test cihazlari', 'bağlantı test cihazları'),
    ('metre dogrulugu', 'metre doğruluğu'),
    ('elektrik testi', 'elektrik testi'),
    ('sinyal testi', 'sinyal testi'),
    ('test ekipmani kalibrasyonu', 'test ekipmanı kalibrasyonu'),
    ('test prosedurleri', 'test prosedürleri'),
    ('cift bobinli metreler', 'çift bobinli metreler'),
    ('AC testi', 'AC testi'),
    ('izolasyon direnci', 'izolasyon direnci'),
    ('aku testi', 'akü testi'),
    ('baglanti ve topraklama testleri', 'bağlantı ve topraklama testleri'),
    
    # Engineering drawings
    ('teknik cizimler', 'teknik çizimler'),
    ('muhendislik standartlari', 'mühendislik standartları'),
    ('projeksiyon sembolleri', 'projeksiyon sembolleri'),
    ('kesit gorunumleri', 'kesit görünümleri'),
    ('tolerans seviyeleri', 'tolerans seviyeleri'),
    ('malzeme ozellikleri', 'malzeme özellikleri'),
    ('cizim tanimlamasi', 'çizim tanımlaması'),
    ('geometrik boyutlandirma ve tolerans', 'geometrik boyutlandırma ve tolerans'),
    ('eskiz cizimi', 'eskiz çizimi'),
    ('sematikler', 'şematikler'),
    ('montaj diyagramlari', 'montaj diyagramları'),
    ('kaynak sembolleri', 'kaynak sembolleri'),
    ('uretim standartlari', 'üretim standartları'),
    ('CAD cizimleri', 'CAD çizimleri'),
    ('imalat cizimleri', 'imalat çizimleri'),
    ('uluslararasi standartlar', 'uluslararası standartlar'),
    ('mekanik cizimler', 'mekanik çizimler'),
    ('tasarim cizimleri', 'tasarım çizimleri'),
    
    # Riveting
    ('percinleme teknikleri', 'perçinleme teknikleri'),
    ('dolu percinler', 'dolu perçinler'),
    ('percin turleri', 'perçin türleri'),
    ('percin tanimlamasi', 'perçin tanımlaması'),
    ('percin boyutlandirma', 'perçin boyutlandırma'),
    ('percin yerlesimi', 'perçin yerleşimi'),
    ('percin montaji', 'perçin montajı'),
    ('percin boslugu', 'perçin boşluğu'),
    ('percin kavrama uzunlugu', 'perçin kavrama uzunluğu'),
    ('percin paylari', 'perçin payları'),
    ('baglanti elemanlari', 'bağlantı elemanları'),
    ('percinleme aletleri', 'perçinleme aletleri'),
    ('pnomatik percinleyiciler', 'pnömatik perçinleyiciler'),
    ('elle percinleme', 'elle perçinleme'),
    ('percin muayenesi', 'perçin muayenesi'),
    ('percin sokumu', 'perçin sökümü'),
    ('percin kusurlari', 'perçin kusurları'),
    ('gomme percinleme', 'gömme perçinleme'),
    ('havsa basli percinler', 'havşa başlı perçinler'),
    ('percin basi turleri', 'perçin başı türleri'),
    ('percinleme prosedurleri', 'perçinleme prosedürleri'),
    
    # Bearings
    ('bilyali yataklar', 'bilyalı yataklar'),
    ('makarali yataklar', 'makaralı yataklar'),
    ('yatak turleri', 'yatak türleri'),
    ('yatak muayenesi', 'yatak muayenesi'),
    ('yatak yaglamasi', 'yatak yağlaması'),
    ('yatak temizligi', 'yatak temizliği'),
    ('yatak sokumu', 'yatak sökümü'),
    ('yatak arizasi', 'yatak arızası'),
    ('acisal temasli yataklar', 'açısal temaslı yataklar'),
    ('eksenel yataklar', 'eksenel yataklar'),
    ('silindirik makarali yataklar', 'silindirik makaralı yataklar'),
    ('kuresel makarali yataklar', 'küresel makaralı yataklar'),
    ('yatak kusurlari', 'yatak kusurları'),
    ('yatak contalari', 'yatak contaları'),
    ('yatak malzemeleri', 'yatak malzemeleri'),
    ('yatak boslugu', 'yatak boşluğu'),
    ('yatak asinmasi', 'yatak aşınması'),
    ('yatak bakimi', 'yatak bakımı'),
    ('yatak degisimi', 'yatak değişimi'),
    ('yatak testi', 'yatak testi'),
    ('yatak toleranslari', 'yatak toleransları'),
    
    # Welding
    ('kaynak teknikleri', 'kaynak teknikleri'),
    ('sert lehim yontemleri', 'sert lehim yöntemleri'),
    ('lehimleme', 'lehimleme'),
    ('yumusak lehimleme', 'yumuşak lehimleme'),
    ('sert lehimleme', 'sert lehimleme'),
    ('gumus lehimleme', 'gümüş lehimleme'),
    ('TIG kaynagi', 'TIG kaynağı'),
    ('MIG kaynagi', 'MIG kaynağı'),
    ('elle metal ark kaynagi', 'elle metal ark kaynağı'),
    ('kaynak muayeneleri', 'kaynak muayeneleri'),
    ('kaynak kusurlari', 'kaynak kusurları'),
    ('kaynak guvenligi', 'kaynak güvenliği'),
    ('eritkenler', 'eritkenler'),
    ('dolgu cubuklari', 'dolgu çubukları'),
    ('havya', 'havya'),
    ('yapistirici ajanlar', 'yapıştırıcı ajanlar'),
    ('yapistirici ile birlestirme', 'yapıştırıcı ile birleştirme'),
    ('kaynak muayenesi', 'kaynak muayenesi'),
    ('sert lehim malzemeleri', 'sert lehim malzemeleri'),
    ('kaynak guvenlik ekipmani', 'kaynak güvenlik ekipmanı'),
    ('yangin riskleri', 'yangın riskleri'),
    ('kaynak aletleri', 'kaynak aletleri'),
    
    # Disassembly & Repair
    ('sokme teknikleri', 'sökme teknikleri'),
    ('muayene yontemleri', 'muayene yöntemleri'),
    ('onarim prosedurleri', 'onarım prosedürleri'),
    ('montaj teknikleri', 'montaj teknikleri'),
    ('bilesen sokumu', 'bileşen sökümü'),
    ('yapisal onarimlar', 'yapısal onarımlar'),
    ('percin onarimlari', 'perçin onarımları'),
    ('bilesen muayenesi', 'bileşen muayenesi'),
    ('parca degisimi', 'parça değişimi'),
    ('hasar degerlendirmesi', 'hasar değerlendirmesi'),
    ('parca tanimlamasi', 'parça tanımlaması'),
    ('onarim kitleri', 'onarım kitleri'),
    ('onarim aletleri', 'onarım aletleri'),
    ('hasar siniflandirmasi', 'hasar sınıflandırması'),
    ('yapisal analiz', 'yapısal analiz'),
    ('onarim dokumantasyonu', 'onarım dokümantasyonu'),
    ('montaj standartlari', 'montaj standartları'),
    ('muayene standartlari', 'muayene standartları'),
    ('baglanti elemani montaji', 'bağlantı elemanı montajı'),
    
    # Aircraft structures
    ('govde', 'gövde'),
    ('kanat', 'kanat'),
    ('kuyruk takimi', 'kuyruk takımı'),
    ('stabilizor', 'stabilizör'),
    ('dumen', 'dümen'),
    ('irtifa dumeni', 'irtifa dümeni'),
    ('kanatcik', 'kanatçık'),
    ('flap', 'flap'),
    ('slat', 'slat'),
    ('fren kanadi', 'fren kanadı'),
    ('inis takimi', 'iniş takımı'),
    ('burun takimi', 'burun takımı'),
    ('ana takimi', 'ana takımı'),
    ('motor yuvasi', 'motor yuvası'),
    ('pilon', 'pilon'),
    ('karenaj', 'karenaj'),
    
    # Hydraulic systems
    ('hidrolik sivi', 'hidrolik sıvı'),
    ('hidrolik pompa', 'hidrolik pompa'),
    ('hidrolik depo', 'hidrolik depo'),
    ('hidrolik hat', 'hidrolik hat'),
    ('hidrolik aktuator', 'hidrolik aktüatör'),
    ('hidrolik valf', 'hidrolik valf'),
    ('basinc gostergesi', 'basınç göstergesi'),
    ('akumulator', 'akümülatör'),
    ('hidrolik filtre', 'hidrolik filtre'),
    ('servo valf', 'servo valf'),
    ('hidrolik motor', 'hidrolik motor'),
    ('guc paketi', 'güç paketi'),
    ('hidrolik conta', 'hidrolik conta'),
    ('basinc tahliye valfi', 'basınç tahliye valfi'),
    ('hidrolik silindir', 'hidrolik silindir'),
    ('cek valf', 'çek valf'),
    
    # Electrical systems
    ('jenerator', 'jeneratör'),
    ('batarya', 'batarya'),
    ('devre kesici', 'devre kesici'),
    ('bara', 'bara'),
    ('transformator', 'transformatör'),
    ('invertor', 'invertör'),
    ('redresor', 'redresör'),
    ('role', 'röle'),
    ('gerilim regulatoru', 'gerilim regülatörü'),
    ('akim sinirlandirici', 'akım sınırlandırıcı'),
    ('toprak hatasi', 'toprak hatası'),
    ('yuk atma', 'yük atma'),
    ('temel bara', 'temel bara'),
    ('acil bara', 'acil bara'),
    ('harici guc', 'harici güç'),
    ('APU jeneratori', 'APU jeneratörü'),
    
    # Fuel systems
    ('yakit tanki', 'yakıt tankı'),
    ('yakit pompasi', 'yakıt pompası'),
    ('yakit filtresi', 'yakıt filtresi'),
    ('yakit hatti', 'yakıt hattı'),
    ('yakit valfi', 'yakıt valfi'),
    ('yakit selektoru', 'yakıt selektörü'),
    ('yakit gostergesi', 'yakıt göstergesi'),
    ('yakit kapagi', 'yakıt kapağı'),
    ('yakit havalandirma', 'yakıt havalandırma'),
    ('yakit suzgeci', 'yakıt süzgeci'),
    ('capraz besleme valfi', 'çapraz besleme valfi'),
    ('yakit miktar gostergesi', 'yakıt miktar göstergesi'),
    ('yakit isitici', 'yakıt ısıtıcı'),
    ('su ayirici', 'su ayırıcı'),
    ('yakit bosaltma', 'yakıt boşaltma'),
    ('merkez tank', 'merkez tank'),
    
    # Pneumatic systems  
    ('kanama havasi', 'kanama havası'),
    ('pnomatik valf', 'pnömatik valf'),
    ('klima', 'klima'),
    ('basinlandirma', 'basınlandırma'),
    ('cikis valfi', 'çıkış valfi'),
    ('paket valfi', 'paket valfi'),
    ('kabin irtifasi', 'kabin irtifası'),
    ('diferansiyel basinc', 'diferansiyel basınç'),
    ('hava dongu makinesi', 'hava döngü makinesi'),
    ('isi degistirici', 'ısı değiştirici'),
    ('karisim valfi', 'karışım valfi'),
    ('resirkulasyon fani', 'resirkülasyon fanı'),
    ('motor kanamasi', 'motor kanaması'),
    ('APU kanamasi', 'APU kanaması'),
    ('kanat buz onleme', 'kanat buz önleme'),
    ('yagmur itici', 'yağmur itici'),
    
    # Flight controls
    ('kumanda kolonu', 'kumanda kolonu'),
    ('yan kumanda', 'yan kumanda'),
    ('pedallar', 'pedallar'),
    ('trim kanati', 'trim kanadı'),
    ('elektrikli kumanda', 'elektrikli kumanda'),
    ('ucus bilgisayari', 'uçuş bilgisayarı'),
    ('kumanda kablosu', 'kumanda kablosu'),
    ('it-cek cubugu', 'it-çek çubuğu'),
    ('kol mekanizmasi', 'kol mekanizması'),
    ('tork tubu', 'tork tübü'),
    ('otopilot servo', 'otopilot servo'),
    ('his unitesi', 'his ünitesi'),
    ('kumanda sarsici', 'kumanda sarsıcı'),
    ('kumanda itici', 'kumanda itici'),
    ('sapma sondurucusu', 'sapma söndürücüsü'),
    ('stol korumasi', 'stol koruması'),
    
    # Lockout tagout
    ('kilitleme', 'kilitleme'),
    ('etiketleme', 'etiketleme'),
    ('enerji izolasyonu', 'enerji izolasyonu'),
    ('tehlike etiketi', 'tehlike etiketi'),
    ('dikkat etiketi', 'dikkat etiketi'),
    ('hizmet disi etiketi', 'hizmet dışı etiketi'),
    ('asma kilit', 'asma kilit'),
    ('kilit baglamasi', 'kilit bağlaması'),
    ('sifir enerji durumu', 'sıfır enerji durumu'),
    ('dogrulama', 'doğrulama'),
    ('yetkili personel', 'yetkili personel'),
    ('etkilenen personel', 'etkilenen personel'),
    ('grup kilitleme', 'grup kilitleme'),
    ('vardiya degisimi', 'vardiya değişimi'),
    ('kaldir proseduru', 'kaldır prosedürü'),
    ('enerji kaynagi', 'enerji kaynağı'),
    
    # Confined space
    ('giris izni', 'giriş izni'),
    ('atmosfer testi', 'atmosfer testi'),
    ('havalandirma', 'havalandırma'),
    ('oksijen seviyesi', 'oksijen seviyesi'),
    ('zehirli gaz', 'zehirli gaz'),
    ('yanici gaz', 'yanıcı gaz'),
    ('giris supervisoru', 'giriş süpervizörü'),
    ('refakatci', 'refakatçi'),
    ('giren kisi', 'giren kişi'),
    ('kurtarma ekibi', 'kurtarma ekibi'),
    ('iletisim sistemi', 'iletişim sistemi'),
    ('acil cikarma', 'acil çıkarma'),
    ('geri cekim sistemi', 'geri çekim sistemi'),
    ('hava monitoru', 'hava monitörü'),
    ('izin iptali', 'izin iptali'),
    
    # Fall protection
    ('dusme tutucu', 'düşme tutucu'),
    ('guvenlik kemeri', 'güvenlik kemeri'),
    ('baglanti noktasi', 'bağlantı noktası'),
    ('bag ipi', 'bağ ipi'),
    ('kendi cekilen halat', 'kendi çekilen halat'),
    ('sok emici', 'şok emici'),
    ('on kenar', 'ön kenar'),
    ('dusme mesafesi', 'düşme mesafesi'),
    ('korkuluk', 'korkuluk'),
    ('guvenlik agi', 'güvenlik ağı'),
    ('kisisel dusme sinirlandirici', 'kişisel düşme sınırlandırıcı'),
    ('halat tutucu', 'halat tutucu'),
    ('tam vucut kemeri', 'tam vücut kemeri'),
    ('sirt halkasi', 'sırt halkası'),
    ('kurtarma plani', 'kurtarma planı'),
    ('yetkili kisi', 'yetkili kişi'),
    
    # Hot work
    ('sicak calisma izni', 'sıcak çalışma izni'),
    ('yangin nobeti', 'yangın nöbeti'),
    ('kaynak perdesi', 'kaynak perdesi'),
    ('kivilcim kontrolu', 'kıvılcım kontrolü'),
    ('yangin battaniyesi', 'yangın battaniyesi'),
    ('yanici malzeme', 'yanıcı malzeme'),
    ('temizlik mesafesi', 'temizlik mesafesi'),
    ('yanmaz', 'yanmaz'),
    ('geri tepme tutucu', 'geri tepme tutucu'),
    ('arindirma', 'arındırma'),
    ('inertleme', 'inertleme'),
    ('gaz tupu depolama', 'gaz tüpü depolama'),
    ('tup ayirma', 'tüp ayırma'),
    ('is sonrasi muayene', 'iş sonrası muayene'),
    ('yangin nobeti suresi', 'yangın nöbeti süresi'),
    
    # Chemical safety
    ('malzeme guvenlik formu', 'malzeme güvenlik formu'),
    ('kimyasal etiketi', 'kimyasal etiketi'),
    ('tehlike sembolu', 'tehlike sembolü'),
    ('KKE gereksinimi', 'KKE gereksinimi'),
    ('maruziyet limiti', 'maruziyet limiti'),
    ('havalandirma gereksinimi', 'havalandırma gereksinimi'),
    ('dokuntu kiti', 'döküntü kiti'),
    ('goz yikama istasyonu', 'göz yıkama istasyonu'),
    ('kimyasal depolama', 'kimyasal depolama'),
    ('uyumsuz kimyasallar', 'uyumsuz kimyasallar'),
    ('ikincil cevirme', 'ikincil çevirme'),
    ('kimyasal atik', 'kimyasal atık'),
    ('dekontaminasyon', 'dekontaminasyon'),
    ('ilk yardim onlemleri', 'ilk yardım önlemleri'),
    ('acil dus', 'acil duş'),
    ('kimyasal envanteri', 'kimyasal envanteri'),
    
    # Electrical safety
    ('elektrik carpmasi', 'elektrik çarpması'),
    ('topraklama', 'topraklama'),
    ('izolasyon', 'izolasyon'),
    ('gerilim', 'gerilim'),
    ('amper', 'amper'),
    ('canli kablo', 'canlı kablo'),
    ('devre test cihazi', 'devre test cihazı'),
    ('izoleli aletler', 'izoleli aletler'),
    ('ark parlamasi', 'ark parlaması'),
    ('ark patlamasi', 'ark patlaması'),
    ('elektrik yaniklari', 'elektrik yanıkları'),
    ('toprak hatasi devre kesici', 'toprak hatası devre kesici'),
    ('elektrik panosu guvenligi', 'elektrik panosu güvenliği'),
    ('enerji kesme', 'enerji kesme'),
    ('dogrulama cihazi', 'doğrulama cihazı'),
    ('sinirlar', 'sınırlar'),
    
    # Emergency evacuation
    ('tahliye plani', 'tahliye planı'),
    ('tahliye yolu', 'tahliye yolu'),
    ('alarm sinyali', 'alarm sinyali'),
    ('yoklama', 'yoklama'),
    ('kisi sayimi', 'kişi sayımı'),
    ('tahliye tatbikati', 'tahliye tatbikatı'),
    ('kat gorevlisi', 'kat görevlisi'),
    ('tarama ekibi', 'tarama ekibi'),
    ('siginak alani', 'sığınak alanı'),
    ('merdiven boslugu', 'merdiven boşluğu'),
    ('tehlike bitti sinyali', 'tehlike bitti sinyali'),
    ('yeniden giris proseduru', 'yeniden giriş prosedürü'),
    ('hesap verebilirlik', 'hesap verebilirlik'),
    ('ozel ihtiyac tahliyesi', 'özel ihtiyaç tahliyesi'),
    
    # Fire emergency
    ('PASS teknigi', 'PASS tekniği'),
    ('pimi cek', 'pimi çek'),
    ('memesini hedefle', 'memesini hedefle'),
    ('kolu sik', 'kolu sık'),
    ('saga sola surukle', 'sağa sola sürükle'),
    ('yangin ucgeni', 'yangın üçgeni'),
    ('sinif A yangin', 'sınıf A yangın'),
    ('sinif B yangin', 'sınıf B yangın'),
    ('sinif C yangin', 'sınıf C yangın'),
    ('sinif D yangin', 'sınıf D yangın'),
    ('duman solunumu', 'duman solunumu'),
    ('dur yat yuvarlan', 'dur yat yuvarlan'),
    ('yangin bastirma sistemi', 'yangın bastırma sistemi'),
    ('halon sistemi', 'halon sistemi'),
    ('yangin sorusturmasi', 'yangın soruşturması'),
    ('yangin hasar degerlendirmesi', 'yangın hasar değerlendirmesi'),
    
    # Medical emergency
    ('tibbi acil durum', 'tıbbi acil durum'),
    ('ilk mudahaleci', 'ilk müdahaleci'),
    ('yasam belirtileri', 'yaşam belirtileri'),
    ('bilincli', 'bilinçli'),
    ('bilincsiz', 'bilinçsiz'),
    ('nabiz', 'nabız'),
    ('solunum', 'solunum'),
    ('tansiyon', 'tansiyon'),
    ('otomatik defibrilator', 'otomatik defibrilatör'),
    ('travma', 'travma'),
    ('kanama', 'kanama'),
    ('turnike', 'turnike'),
    ('omurga yaralanmasi', 'omurga yaralanması'),
    ('hareketsizlestirme', 'hareketsizleştirme'),
    ('tibbi transport', 'tıbbi transport'),
    ('triaj', 'triyaj'),
    
    # Hazmat
    ('dokuntu mudahalesi', 'döküntü müdahalesi'),
    ('cevirme', 'çevirme'),
    ('temizlik', 'temizlik'),
    ('emme', 'emme'),
    ('notralize', 'nötralize'),
    ('bertaraf', 'bertaraf'),
    ('dekontaminasyon bolgesi', 'dekontaminasyon bölgesi'),
    ('yasak bolge', 'yasak bölge'),
    ('sicak bolge', 'sıcak bölge'),
    ('ilik bolge', 'ılık bölge'),
    ('soguk bolge', 'soğuk bölge'),
    ('seviye A elbise', 'seviye A elbise'),
    ('bagimsiz solunum cihazi', 'bağımsız solunum cihazı'),
    ('kimyasala direncli', 'kimyasala dirençli'),
    ('acil mudahale kilavuzu', 'acil müdahale kılavuzu'),
    
    # Aircraft emergency
    ('acil inis', 'acil iniş'),
    ('cakisma kurtarma', 'çakışma kurtarma'),
    ('itfaiye araci', 'itfaiye aracı'),
    ('kopuk uygulama', 'köpük uygulama'),
    ('kurtarma yolu', 'kurtarma yolu'),
    ('yolcu tahliyesi', 'yolcu tahliyesi'),
    ('acil kaydiran', 'acil kaydıran'),
    ('kanat ustu cikis', 'kanat üstü çıkış'),
    ('carpisma pozisyonu', 'çarpışma pozisyonu'),
    ('kurtulan cikarma', 'kurtulan çıkarma'),
    ('triaj alani', 'triyaj alanı'),
    ('yarali toplama', 'yaralı toplama'),
    ('birlesik komuta', 'birleşik komuta'),
    ('olay komutani', 'olay komutanı'),
    ('karsilikli yardim', 'karşılıklı yardım'),
    ('havaalani acil plan', 'havaalanı acil plan'),
    
    # Communication
    ('mayday cagrisi', 'mayday çağrısı'),
    ('pan-pan cagrisi', 'pan-pan çağrısı'),
    ('acil frekans', 'acil frekans'),
    ('telsiz iletisimi', 'telsiz iletişimi'),
    ('transponder kodu', 'transponder kodu'),
    ('acil isareti', 'acil işareti'),
    ('acil yer vericisi', 'acil yer vericisi'),
    ('cakisma pozisyon gostergesi', 'çakışma pozisyon göstergesi'),
    ('dahili telefon', 'dahili telefon'),
    ('anons sistemi', 'anons sistemi'),
    ('el isareti', 'el işareti'),
    ('acil kod sozcukleri', 'acil kod sözcükleri'),
    ('uydu telefonu', 'uydu telefonu'),
    ('yedek iletisim', 'yedek iletişim'),
    ('tehlike sinyali', 'tehlike sinyali'),
    ('arama kurtarma koordinasyonu', 'arama kurtarma koordinasyonu'),
    
    # First aid
    ('ilk yardim', 'ilk yardım'),
    ('yara', 'yara'),
    ('yanik', 'yanık'),
    ('bilincsizlik', 'bilinçsizlik'),
    ('kalp akciger canlandirma', 'kalp akciğer canlandırma'),
    ('hava yolu', 'hava yolu'),
    ('nefes alma', 'nefes alma'),
    ('dolasim', 'dolaşım'),
    ('steril pansuman', 'steril pansuman'),
    ('gogus kompresyonlari', 'göğüs kompresyonları'),
    ('kurtarma nefesleri', 'kurtarma nefesleri'),
    ('kurtarma pozisyonu', 'kurtarma pozisyonu'),
    ('soluk borusu', 'soluk borusu'),
    ('kirik', 'kırık'),
    ('sok', 'şok'),
    ('kalp durmasi', 'kalp durması'),
    ('yari yuzukoyun pozisyon', 'yarı yüzükoyun pozisyon'),
    ('tehlike-yanit-yardim-hava yolu-nefes-dolasim', 'tehlike-yanıt-yardım-hava yolu-nefes-dolaşım'),
    ('canlandirma', 'canlandırma'),
    
    # Aviation fuels
    ('havacilik yakiti', 'havacılık yakıtı'),
    ('gazyagi', 'gazyağı'),
    ('benzin', 'benzin'),
    ('yakit ikmali', 'yakıt ikmali'),
    ('statik elektrik', 'statik elektrik'),
    ('yakit buhari', 'yakıt buharı'),
    ('baglama kablosu', 'bağlama kablosu'),
    ('yakit dokulmesi', 'yakıt dökülmesi'),
    ('buhar basinci', 'buhar basıncı'),
    ('parlama noktasi', 'parlama noktası'),
    ('yakit kirliligi', 'yakıt kirliliği'),
    ('parafin', 'parafin'),
    ('iletkenlik', 'iletkenlik'),
    ('topraklama kayisi', 'topraklama kayışı'),
    ('anti-statik katki', 'anti-statik katkı'),
    
    # Fire fighting
    ('kopuklu sondurucu', 'köpüklü söndürücü'),
    ('CO2 sondurucu', 'CO2 söndürücü'),
    ('kuru tozlu sondurucu', 'kuru tozlu söndürücü'),
    ('yangin hortumu', 'yangın hortumu'),
    ('yangin muslugu', 'yangın musluğu'),
    ('yagmurlama sistemi', 'yağmurlama sistemi'),
    ('duman dedektoru', 'duman dedektörü'),
    ('yangin alarm paneli', 'yangın alarm paneli'),
    ('acil durum aydinlatmasi', 'acil durum aydınlatması'),
    ('yangin kapisi', 'yangın kapısı'),
    ('sondurucu muayenesi', 'söndürücü muayenesi'),
    ('yangin tatbikati', 'yangın tatbikatı'),
    ('yangin ekibi', 'yangın ekibi'),
    ('itfaiye istasyonu', 'itfaiye istasyonu'),
    
    # Ground handling
    ('yer hizmetleri', 'yer hizmetleri'),
    ('geri itme', 'geri itme'),
    ('cekilme', 'çekilme'),
    ('park yonlendirme', 'park yönlendirme'),
    ('takozlar', 'takozlar'),
    ('tekerlek takozu', 'tekerlek takozu'),
    ('cekme cubugu', 'çekme çubuğu'),
    ('yer guc unitesi', 'yer güç ünitesi'),
    ('hava baslangic unitesi', 'hava başlangıç ünitesi'),
    ('bagaj yukleyici', 'bagaj yükleyici'),
    ('ikram araci', 'ikram aracı'),
    ('tuvalet servisi', 'tuvalet servisi'),
    ('buz cozme araci', 'buz çözme aracı'),
    ('yakit kamyonu', 'yakıt kamyonu'),
    ('yolcu merdiveni', 'yolcu merdiveni'),
    ('koprulu binis', 'köprülü biniş'),
    
    # Aircraft movement
    ('taksi yapma', 'taksi yapma'),
    ('pist', 'pist'),
    ('taksi yolu', 'taksi yolu'),
    ('apron', 'apron'),
    ('park yeri', 'park yeri'),
    ('bekleme noktasi', 'bekleme noktası'),
    ('izin', 'izin'),
    ('yer kontrolu', 'yer kontrolü'),
    ('kanat gozcusu', 'kanat gözcüsü'),
    ('takip araci', 'takip aracı'),
    ('burun tekerlek direksiyonu', 'burun tekerlek direksiyonu'),
    ('fren birakma', 'fren bırakma'),
    ('motor calistirma izni', 'motor çalıştırma izni'),
    ('geri itme izni', 'geri itme izni'),
    ('taksi talimatlari', 'taksi talimatları'),
    ('pist ihlali', 'pist ihlali'),
    
    # Flight deck
    ('kokpit', 'kokpit'),
    ('ucus guverte', 'uçuş güverte'),
    ('gosterge paneli', 'gösterge paneli'),
    ('kumanda kolu', 'kumanda kolu'),
    ('gaz kolu', 'gaz kolu'),
    ('dumen pedallari', 'dümen pedalları'),
    ('otopilot', 'otopilot'),
    ('ucus yonetim sistemi', 'uçuş yönetim sistemi'),
    ('birincil ucus ekrani', 'birincil uçuş ekranı'),
    ('navigasyon ekrani', 'navigasyon ekranı'),
    ('motor gostergeleri', 'motor göstergeleri'),
    ('tavan paneli', 'tavan paneli'),
    ('merkez konsol', 'merkez konsol'),
    ('ucus kontrol unitesi', 'uçuş kontrol ünitesi'),
    ('yedek gostergeler', 'yedek göstergeler'),
    ('devre kesiciler', 'devre kesiciler'),
]

# Apply replacements
for old, new in replacements:
    content = content.replace(old, new)

# Additional pass for remaining common patterns
additional_fixes = [
    ('Dokumantasyonu', 'Dokümantasyonu'),
    ('Cizimleri', 'Çizimleri'),
    ('Ekipmanlari', 'Ekipmanları'),
    ('Uygulamalari', 'Uygulamaları'),  
    ('Sistemleri', 'Sistemleri'),
    ('Prosedurleri', 'Prosedürleri'),
    ('atolye', 'atölye'),
    ('Atolye', 'Atölye'),
    ('isyeri', 'işyeri'),
    ('Isyeri', 'İşyeri'),
    ('ucak', 'uçak'),
    ('Ucak', 'Uçak'),
    ('ucus', 'uçuş'),
    ('Ucus', 'Uçuş'),
    ('yakit', 'yakıt'),
    ('Yakit', 'Yakıt'),
    ('yangin', 'yangın'),
    ('Yangin', 'Yangın'),
    ('sondurucu', 'söndürücü'),
    ('guvenlik', 'güvenlik'),
    ('Guvenlik', 'Güvenlik'),
    ('guvenligi', 'güvenliği'),
    ('Guvenligi', 'Güvenliği'),
    ('bakim', 'bakım'),
    ('Bakim', 'Bakım'),
    ('onarim', 'onarım'),
    ('Onarim', 'Onarım'),
    ('calisma', 'çalışma'),
    ('Calisma', 'Çalışma'),
    ('degerlendirmesi', 'değerlendirmesi'),
    ('dokumantasyonu', 'dokümantasyonu'),
    ('prosedurleri', 'prosedürleri'),
    ('UNITE Kisisel', 'ÜNİTE Kişisel'),
    ('UNITE', 'ÜNİTE'),
]

for old, new in additional_fixes:
    content = content.replace(old, new)

# Write the file
with open('lib/data/vocabulary_data.dart', 'w', encoding='utf-8') as f:
    f.write(content)

print("Türkçe karakter düzeltmeleri tamamlandı!")
