// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpPCQKh-eK8XKLOyL8_8wCQYG0q9zZF7A',
    appId: '1:1031597033876:web:7e9b1e0f5a8c0e9f5b5e5e',
    messagingSenderId: '1031597033876',
    projectId: 'allien-4e4f1',
    authDomain: 'allien-4e4f1.firebaseapp.com',
    storageBucket: 'allien-4e4f1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpPCQKh-eK8XKLOyL8_8wCQYG0q9zZF7A',
    appId: '1:1031597033876:android:7e9b1e0f5a8c0e9f5b5e5e',
    messagingSenderId: '1031597033876',
    projectId: 'allien-4e4f1',
    authDomain: 'allien-4e4f1.firebaseapp.com',
    storageBucket: 'allien-4e4f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpPCQKh-eK8XKLOyL8_8wCQYG0q9zZF7A',
    appId: '1:1031597033876:ios:7e9b1e0f5a8c0e9f5b5e5e',
    messagingSenderId: '1031597033876',
    projectId: 'allien-4e4f1',
    authDomain: 'allien-4e4f1.firebaseapp.com',
    storageBucket: 'allien-4e4f1.firebasestorage.app',
    iosBundleId: 'com.example.englishAircraft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpPCQKh-eK8XKLOyL8_8wCQYG0q9zZF7A',
    appId: '1:1031597033876:macos:7e9b1e0f5a8c0e9f5b5e5e',
    messagingSenderId: '1031597033876',
    projectId: 'allien-4e4f1',
    authDomain: 'allien-4e4f1.firebaseapp.com',
    storageBucket: 'allien-4e4f1.firebasestorage.app',
    iosBundleId: 'com.example.englishAircraft',
  );
}
